#!/bin/bash
# SPRINT 1 QUICK START - Implement All Changes
# Run this guide step-by-step to apply Sprint 1 improvements

echo "=========================================="
echo "SPRINT 1: FOUNDATION & SECURITY"
echo "=========================================="
echo ""
echo "What you'll get:"
echo "✅ Comprehensive testing suite"
echo "✅ Input validation & sanitization"
echo "✅ Global error handling"
echo "✅ React error boundaries"
echo "✅ Security hardening"
echo ""

# Step 0: Install dependencies
echo "STEP 0: Installing dependencies..."
echo "→ npm install --save-dev vitest @testing-library/react"
echo "→ Status: ✅ ALREADY DONE"
echo ""

# Step 1: Run tests to verify setup
echo "STEP 1: Verify testing framework"
echo "→ Command: npm run test"
echo "→ Expected: All tests pass ✅"
echo ""

# Step 2: Review documentation
echo "STEP 2: Read the guides (15 minutes)"
echo "→ Read: SPRINT1_SETUP_GUIDE.md"
echo "→ Read: SPRINT1_COMPLETE.md"
echo "→ Reference: docs/BUG_FIXES_SPRINT1.ts"
echo "→ Reference: docs/SERVER_INTEGRATION.ts"
echo ""

# Step 3: Apply error handling
echo "STEP 3: Add error handlers to routes (1-2 hours)"
echo ""
echo "  3a. Add imports to server/routes.ts:"
echo "    import { asyncHandler, AppError, errorHandler, notFoundHandler } from './middleware/errorHandler';"
echo ""
echo "  3b. Wrap async routes with asyncHandler:"
echo "    app.post('/api/subscriptions',"
echo "      asyncHandler(async (req, res) => { ... })"
echo "    );"
echo ""
echo "  3c. Add handlers at END of server/index.ts (AFTER all routes):"
echo "    app.use(notFoundHandler);"
echo "    app.use(errorHandler);"
echo ""

# Step 4: Add validation
echo "STEP 4: Add input validation (1-2 hours)"
echo ""
echo "  4a. Define Zod schemas for your routes"
echo "  4b. Add validateBody middleware to POST/PUT routes"
echo "  4c. Test with invalid inputs"
echo ""

# Step 5: Test everything
echo "STEP 5: Test the implementation (30 minutes)"
echo ""
echo "  5a. Run tests: npm run test"
echo "  5b. Start dev server: npm run dev"
echo "  5c. Test error cases in browser:"
echo "    - Try to create subscription with negative amount"
echo "    - Try to access data without logging in"
echo "    - Check error messages are user-friendly"
echo ""

# Step 6: Verify error boundary
echo "STEP 6: Verify error boundary (15 minutes)"
echo ""
echo "  6a. Error boundary is already wrapping your App ✅"
echo "  6b. Test it: trigger an error in a component"
echo "  6c. Verify fallback UI shows"
echo ""

echo "=========================================="
echo "TIMELINE"
echo "=========================================="
echo "Phase A (Error Handlers):  1-2 hours"
echo "Phase B (Validation):      1-2 hours"
echo "Phase C (Sanitization):    30 minutes"
echo "Phase D (Testing):         15 minutes"
echo "Phase E (Verification):    15 minutes"
echo ""
echo "TOTAL: ~4-5 hours of development work"
echo ""

echo "=========================================="
echo "KEY FILES TO WORK WITH"
echo "=========================================="
echo "server/routes.ts                  - Add error handling here"
echo "server/middleware/errorHandler.ts - Already created ✅"
echo "server/middleware/validation.ts   - Already created ✅"
echo "client/src/App.tsx                - Already using ErrorBoundary ✅"
echo "client/src/components/error-boundary.tsx - Already created ✅"
echo "tests/                            - Test files (3 suites) ✅"
echo ""

echo "=========================================="
echo "COMMON PATTERNS TO FOLLOW"
echo "=========================================="
echo ""
echo "Pattern 1: Async route with error handling"
echo "---"
echo "app.post('/api/endpoint',"
echo "  validateBody(schema),"
echo "  asyncHandler(async (req, res) => {"
echo "    if (!req.session?.user) throw new UnauthorizedError();"
echo "    const result = await operation();"
echo "    res.json(result);"
echo "  })"
echo ");"
echo ""

echo "Pattern 2: Validate positive amount"
echo "---"
echo "if (req.body.amount <= 0) {"
echo "  throw new AppError(400, 'Amount must be positive');"
echo "}"
echo ""

echo "Pattern 3: Check authorization"
echo "---"
echo "if (data.user_id !== userId) {"
echo "  throw new ForbiddenError('Access denied');"
echo "}"
echo ""

echo "=========================================="
echo "TESTING CHECKLIST"
echo "=========================================="
echo "[ ] npm run test passes"
echo "[ ] npm run test:coverage works"
echo "[ ] Error boundary in App.tsx"
echo "[ ] POST /api/subscriptions validates amount > 0"
echo "[ ] DELETE /api/subscriptions/:id returns 404 if not found"
echo "[ ] Unauthorized request throws 401"
echo "[ ] Forbidden request throws 403"
echo "[ ] Internal error doesn't expose details in prod"
echo "[ ] All error responses are JSON format"
echo ""

echo "=========================================="
echo "NEXT SPRINT (Sprint 2)"
echo "=========================================="
echo "✓ Database optimization & indexing"
echo "✓ Caching with Redis"
echo "✓ Pagination for large datasets"
echo "✓ Sentry integration for error tracking"
echo "✓ Production deployment setup"
echo ""

echo "=========================================="
echo "📚 DOCUMENTATION"
echo "=========================================="
echo "Start here: SPRINT1_SETUP_GUIDE.md"
echo "Integration: docs/SERVER_INTEGRATION.ts"
echo "Bug fixes: docs/BUG_FIXES_SPRINT1.ts"
echo "Summary: SPRINT1_COMPLETE.md"
echo ""

echo "=========================================="
echo "Ready to start? Follow the steps above!"
echo "=========================================="
